const db = [
    {
        id: 0,
        name: "Nike Air Max Pre-Day",
        _status: "Sustainable Materials",
        price: "3,829,000 đ",
        text: "Taking the classic look of heritage Nike Running into a new realm, the Nike Air Max Pre-Day brings you a fast-paced look that's ready for today's world.A true nod to the past with a design made from at least 20% recycled material by weight, it keeps the retro-athletics aesthetic alive.A new Air window energises the look, mixing head-turning style with unbelievably soft cushioning.",
        img1: "./MEDIA/0/air-max-pre-day-shoes-jMh2rB (1).jpg",
        img2: "./MEDIA/0/air-max-pre-day-shoes-jMh2rB (2).jpg",
        img3: "./MEDIA/0/air-max-pre-day-shoes-jMh2rB.jpg",
        img4: "./MEDIA/0/air-max-pre-day-shoes-jMh2rB3.jpg"
    },
    {
        id: 1,
        name: "Nike Air Presto x Hello Kitty ®",
        _status: "",
        price: "4,109,000₫",
        text: "Let myth become reality and step into a world of rainbows and sunshine with the Nike Air Presto x Hello Kitty. From the custom-moulded Hello Kitty heel to her red bow on the tongue, your favourite super-cute cartoon character joins your journey.",
        img1: "./MEDIA/1/1.jpg",
        img2: "./MEDIA/1/2.jpg",
        img3: "./MEDIA/1/3.jpg",
        img4: "./MEDIA/1/4.jpg"
    },
    {
        id: 2,
        name: "Nike Go FlyEase",
        _status: "Bestseller",
        price: "3,829,000₫",
        text: "Ditch the laces and get outside. These kicks feature Nike's revolutionary FlyEase technology, making on-and-off a breeze. With a heel that pivots open for a totally hands-free entry, they're great for people with limited mobility—or anyone who wants a quicker way to get going.",
        img1: "./MEDIA/2/1.jpg",
        img2: "./MEDIA/2/2.jpg",
        img3: "./MEDIA/2/3.jpg",
        img4: "./MEDIA/2/4.jpg"
    },
    {
        id: 3,
        name: "Nike ZoomX Invincible Run Flyknit 2",
        _status: "",
        price: "5,279,000₫",
        text: "Keep pushing your runs to the limit. The Nike ZoomX Invincible Run Flyknit 2 keeps you going with the same super-soft feel that lets you feel the potential when your foot hits the pavement. We created the shoe with plenty of springy responsiveness and our highest level of support to keep you feeling secure and competitive. It's one of our most tested shoes, still designed for you to stay on the road and away from the sidelines.",
        img1: "./MEDIA/3/1.jpg",
        img2: "./MEDIA/3/2.jpg",
        img3: "./MEDIA/3/3.jpg",
        img4: "./MEDIA/3/4.jpg"
    },
    {
        id: 4,
        name: "Nike Air Zoom Pegasus 39",
        _status: "Promo Exclustion",
        price: "5,279,000₫",
        text: "Running is your daily ritual, with every step taking you closer to your personal goal. Let the Nike Air Zoom Pegasus 39 help you ascend to new heights—whether you're training or jogging—with its intuitive design. More lightweight up top than the Pegasus 38 and ideal to wear in any season, it has a supportive sensation to help keep your feet contained, while underfoot cushioning and double Zoom Air units (1 more than the Peg 38) give you an extra pop to your step. Your trusted workhorse with wings is back. Time to fly.",
        img1: "./MEDIA/4/1.png",
        img2: "./MEDIA/4/2.png",
        img3: "./MEDIA/4/3.png",
        img4: "./MEDIA/4/4.png"
    },
    {
        id: 5,
        name: "Nike ZoomX Vaporfly NEXT% 2",
        _status: "",
        price: "7,349,000₫",
        text: "Continue the next evolution of speed with a racing shoe designed to help you chase new goals and records. From a 10K to a marathon, this model has the same responsive cushioning and secure support of previous versions to push you towards your personal best. A redesigned upper helps improve the overall comfort and breathability.",
        img1: "./MEDIA/5/1.jpg",
        img2: "./MEDIA/5/2.jpg",
        img3: "./MEDIA/5/3.jpg",
        img4: "./MEDIA/5/4.jpg"
    },
    {
        id: 6,
        name: "NikeCourt Air Zoom GP Turbo Naomi Osaka",
        _status: "Just In",
        price: "4,409,000₫",
        text: "Tennis matches are fast, fierce and long. The NikeCourt Air Zoom GP Turbo combines a responsive Zoom Air unit with zones of durability, so you can stay fresh longer. For this version, we drew inspiration from Naomi Osaka's 2018 'All smiles' social media post for a special design.",
        img1: "./MEDIA/6/1.jpg",
        img2: "./MEDIA/6/2.jpg",
        img3: "./MEDIA/6/3.jpg",
        img4: "./MEDIA/6/4.jpg"
    },
    {
        id: 7,
        name: "NikeCourt React Vapor NXT",
        _status: "",
        price: "4,699,000₫",
        text: "For the rally that won't relent or the dangling volley that needs to be smashed at the net, go with the next generation of tennis performance. Backed by years of athlete data, it provides the kind of tenacious traction that can help you get to that unreachable ball along the baseline. An innovative cushioning system offers the sort of satisfying support that can help make the difference if your match goes the distance.",
        img1: "./MEDIA/7/1.jpg",
        img2: "./MEDIA/7/2.jpg",
        img3: "./MEDIA/7/3.jpg",
        img4: "./MEDIA/7/4.jpg"
    },
    {
        id: 8,
        name: "NikeCourt Air Zoom Vapor Pro",
        _status: "",
        price: "3,519,000₫",
        text: "The NikeCourt Air Zoom Vapor Pro takes everything you love about the NikeCourt Air Zoom Vapor X and makes it lighter and more supportive. The 3-layer design puts breathability, stability and durability where they're needed most, all while keeping weight at a minimum.",
        img1: "./MEDIA/8/1.jpg",
        img2: "./MEDIA/8/2.jpg",
        img3: "./MEDIA/8/3.jpg",
        img4: "./MEDIA/8/4.jpg"
    },
    {
        id: 9,
        name: "Nike Phantom GT2 Academy MG",
        _status: "",
        price: "2,479,000₫",
        text: "Building on the Phantom GT, the Nike Phantom GT2 MG has an updated design and patterning that is engineered to help you place your shots with pinpoint accuracy. Off-centre lacing provides a clean strike zone to help you dribble, pass and score with precision.",
        img1: "./MEDIA/9/1.jpg",
        img2: "./MEDIA/9/2.jpg",
        img3: "./MEDIA/9/3.jpg",
        img4: "./MEDIA/9/4.jpg"
    },
    {
        id: 10,
        name: "Nike Mercurial Vapor 14 Elite FG",
        _status: "",
        price: "7,319,000₫",
        text: "The Nike Mercurial Vapor 14 Elite FG features a new look with specialised components to let you play your fastest from start to finish. A cushioned insole gives you non-stop comfort, and the innovative plate provides instant responsiveness for quicker cuts at high speeds.",
        img1: "./MEDIA/10/1.jpg",
        img2: "./MEDIA/10/2.jpg",
        img3: "./MEDIA/10/3.jpg",
        img4: "./MEDIA/10/4.jpg"
    },
    {
        id: 11,
        name: "Air Jordan XXXVI PF",
        _status: "",
        price: "5,439,000₫",
        text: "The Air Jordan XXXVI isn't just the next shoe up in the iconic franchise; it's an expression of the drive and energy that sparked a basketball revolution.It's one of the lightest Air Jordan game shoes to date, featuring a minimal but durable leno-weave upper reinforced with a TPU ribbon and synthetic overlays.It also comes equipped with a full-length Zoom Air Strobel unit stitched directly to the upper, stacked with a Zoom Air unit underneath the forefoot, providing a sensation of energy return and elite responsiveness.Step on the court with the confidence that whatever you do—it's light work.This PF version uses an extra-durable outsole that's designed for outdoor courts.",
        img1: "./MEDIA/11/1.jpg",
        img2: "./MEDIA/11/2.jpg",
        img3: "./MEDIA/11/3.jpg",
        img4: "./MEDIA/11/4.jpg"
    },
    {
        id: 12,
        name: "Air Jordan 1 Zoom Cmft",
        _status: "Promo Exclustion",
        price: "4,109,000₫",
        text: "Making iconic style even more comfortable. The Air Jordan 1 Zoom Cmft remakes the 1st Air Jordan with lightweight, low-profile cushioning and elements that improve wearability. Leathers and textiles in the upper have a broken-in feel. A lined, padded collar cups the heel for a secure fit.",
        img1: "./MEDIA/12/1.jpg",
        img2: "./MEDIA/12/2.jpg",
        img3: "./MEDIA/12/3.jpg",
        img4: "./MEDIA/12/4.jpg"
    },
    {
        id: 13,
        name: "Jordan Why Not .5 PF",
        _status: "",
        price: "3,829,000₫",
        text: "Russell Westbrook is fast. The Jordan Why Not .5 helps keep him contained with updated cushioning, data-informed traction and a full-foot fit system that keeps him in control. It has the rugged utility look of a trail running shoe combined with the on-purpose clash of colours and materials at the core of Why Not?        ",
        img1: "./MEDIA/13/1.jpg",
        img2: "./MEDIA/13/2.jpg",
        img3: "./MEDIA/13/3.jpg",
        img4: "./MEDIA/13/4.jpg"
    },
    {
        id: 14,
        name: "Air Jordan XXXVI Low",
        _status: "Just In",
        price: "5,129,000₫",
        text: "From the perimeter to the hoop, take the court with confidence. This is one of the lightest Air Jordan game shoes to date, with a minimal but durable leno-weave upper reinforced with tough plastic details. Meanwhile, Zoom Air cushioning delivers energy return and elite responsiveness. The game asks for everything—now you have the shoe to match.        ",
        img1: "./MEDIA/14/1.jpg",
        img2: "./MEDIA/14/2.jpg",
        img3: "./MEDIA/14/3.jpg",
        img4: "./MEDIA/14/4.jpg"
    },
    {
        id: 15,
        name: "Nike Vista",
        _status: "Just In",
        price: "1,609,000₫",
        text: "With all of the necessary elements you need for a day out (like plush padding and easy-to-style colours), the Nike Vista delivers on less is more. Lightweight, airy and supportive, it lets you bridge city living and nature with the pull of a strap.        ",
        img1: "./MEDIA/15/1.jpg",
        img2: "./MEDIA/15/2.jpg",
        img3: "./MEDIA/15/3.jpg",
        img4: "./MEDIA/15/4.jpg"
    },
]